language: node_js
node_js:
  - 12
cache: npm

git:
  depth: 3
script:
  - yarn build
deploy: 
  provider: pages
  edge: true
  cleanup: true
  keep-history: true
  github-token: '$GITHUB_TOKEN'
  local-dir: dist/
  commit_message: "Deploy Release"
  on:
    branch: gh-pages